/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  Cell,
  Config,
} from './components/cbk-grid/entities';


export namespace Components {

  interface CbkGrid {
    /**
    * The first name
    */
    'config': Config;
    /**
    * The middle name
    */
    'items': Cell[];
  }
  interface CbkGridAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'config'?: Config;
    /**
    * The middle name
    */
    'items'?: Cell[];
  }
}

declare global {
  interface StencilElementInterfaces {
    'CbkGrid': Components.CbkGrid;
  }

  interface StencilIntrinsicElements {
    'cbk-grid': Components.CbkGridAttributes;
  }


  interface HTMLCbkGridElement extends Components.CbkGrid, HTMLStencilElement {}
  var HTMLCbkGridElement: {
    prototype: HTMLCbkGridElement;
    new (): HTMLCbkGridElement;
  };

  interface HTMLElementTagNameMap {
    'cbk-grid': HTMLCbkGridElement
  }

  interface ElementTagNameMap {
    'cbk-grid': HTMLCbkGridElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
