/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  Config,
} from './components/cbk-grid-actions/entities';
import {
  Config as Config2,
} from './components/cbk-grid/entities';


export namespace Components {

  interface CbkGridActions {
    /**
    * 4. Public Property API Config data
    */
    'config': Config;
  }
  interface CbkGridActionsAttributes extends StencilHTMLAttributes {
    /**
    * 4. Public Property API Config data
    */
    'config'?: Config;
    /**
    * 5. Events section
    */
    'onActionClicked'?: (event: CustomEvent) => void;
  }

  interface CbkGrid {
    'clearSelection': () => void;
    /**
    * 4. Public Property API Config data
    */
    'config': Config;
    /**
    * Grid items
    */
    'items': any[];
    /**
    * 8. Public methods API
    */
    'selectAllItems': () => void;
  }
  interface CbkGridAttributes extends StencilHTMLAttributes {
    /**
    * 4. Public Property API Config data
    */
    'config'?: Config;
    /**
    * Grid items
    */
    'items'?: any[];
    /**
    * 5. Events section
    */
    'onSelectionChanged'?: (event: CustomEvent) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'CbkGridActions': Components.CbkGridActions;
    'CbkGrid': Components.CbkGrid;
  }

  interface StencilIntrinsicElements {
    'cbk-grid-actions': Components.CbkGridActionsAttributes;
    'cbk-grid': Components.CbkGridAttributes;
  }


  interface HTMLCbkGridActionsElement extends Components.CbkGridActions, HTMLStencilElement {}
  var HTMLCbkGridActionsElement: {
    prototype: HTMLCbkGridActionsElement;
    new (): HTMLCbkGridActionsElement;
  };

  interface HTMLCbkGridElement extends Components.CbkGrid, HTMLStencilElement {}
  var HTMLCbkGridElement: {
    prototype: HTMLCbkGridElement;
    new (): HTMLCbkGridElement;
  };

  interface HTMLElementTagNameMap {
    'cbk-grid-actions': HTMLCbkGridActionsElement
    'cbk-grid': HTMLCbkGridElement
  }

  interface ElementTagNameMap {
    'cbk-grid-actions': HTMLCbkGridActionsElement;
    'cbk-grid': HTMLCbkGridElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
